const Pokemons = [
  {
    Id: 1,
    name: "Bulbasaur",
    type: "Grass",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
    tag: "001",
    bgColor: "green",
  },
  {
    Id: 2,
    name: "Ivysaur",
    type: "Grass",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png",
    tag: "002",
    bgColor: "green",
  },
  {
    Id: 3,
    name: "Venusaur",
    type: "Grass",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
    tag: "003",
    bgColor: "green",
  },
  {
    Id: 4,
    name: "Charmander",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
    tag: "004",
    bgColor: "red",
  },
  {
    Id: 5,
    name: "Charmeleon",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png",
    tag: "005",
    bgColor: "red",
  },
  {
    Id: 6,
    name: "Charizard",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
    tag: "006",
    bgColor: "red",
  },
  {
    Id: 7,
    name: "Squirtle",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
    tag: "007",
    bgColor: "blue",
  },
  {
    Id: 8,
    name: "	Wartortle",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png",
    tag: "008",
    bgColor: "blue",
  },
  {
    Id: 9,
    name: "Blastoise",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
    tag: "009",
    bgColor: "blue",
  },
  {
    Id: 10,
    name: "Caterpie",
    type: "Bug",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png",
    tag: "010",
    bgColor: "darkgreen",
  },
  {
    Id: 11,
    name: "Metapod",
    type: "Bug",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png",
    tag: "011",
    bgColor: "darkgreen",
  },
  {
    Id: 12,
    name: "Butterfree",
    type: "Bug",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png",
    tag: "012",
    bgColor: "darkgreen",
  },
  {
    Id: 13,
    name: "Weedle",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png",
    tag: "013",
    bgColor: "purple",
  },
  {
    Id: 14,
    name: "Kakuna",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png",
    tag: "014",
    bgColor: "purple",
  },
  {
    Id: 15,
    name: "Beedrill",
    type: "Bug/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png",
    tag: "015",
    bgColor: "purple",
  },
  {
    Id: 16,
    name: "Pidgey",
    type: "Normal/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png",
    tag: "016",
    bgColor: "gray",
  },
  {
    Id: 17,
    name: "Pidgeotto",
    type: "Normal/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png",
    tag: "017",
    bgColor: "gray",
  },
  {
    Id: 18,
    name: "Pidgeot",
    type: "Normal/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
    tag: "018",
    bgColor: "gray",
  },
  {
    Id: 19,
    name: "Rattata",
    type: "Normal",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png",
    tag: "019",
    bgColor: "gray",
  },
  {
    Id: 20,
    name: "Raticate",
    type: "Normal",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png",
    tag: "020",
    bgColor: "gray",
  },
  {
    Id: 21,
    name: "Spearow",
    type: "Normal/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png",
    tag: "021",
    bgColor: "gray",
  },
  {
    Id: 22,
    name: "Fearow",
    type: "Normal/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png",
    tag: "022",
    bgColor: "gray",
  },
  {
    Id: 23,
    name: "Ekans",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png",
    tag: "023",
    bgColor: "purple",
  },
  {
    Id: 24,
    name: "Arbok",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png",
    tag: "024",
    bgColor: "purple",
  },
  {
    Id: 25,
    name: "Pikachu",
    type: "Electric",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
    tag: "025",
    bgColor: "yellow",
  },
  {
    Id: 26,
    name: "Raichu",
    type: "Electric",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
    tag: "026",
    bgColor: "yellow",
  },
  {
    Id: 27,
    name: "Sandshrew",
    type: "Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png",
    tag: "027",
    bgColor: "brown",
  },
  {
    Id: 28,
    name: "Sandslash",
    type: "Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png",
    tag: "028",
    bgColor: "brown",
  },
  {
    Id: 29,
    name: "Nidoran♀",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png",
    tag: "029",
    bgColor: "purple",
  },
  {
    Id: 30,
    name: "Nidorina",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png",
    tag: "030",
    bgColor: "purple",
  },
  {
    Id: 31,
    name: "Nidoqueen",
    type: "Poison/Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png",
    tag: "031",
    bgColor: "purple",
  },
  {
    Id: 32,
    name: "Nidoran♂",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png",
    tag: "032",
    bgColor: "purple",
  },
  {
    Id: 33,
    name: "Nidorino",
    type: "Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png",
    tag: "033",
    bgColor: "purple",
  },
  {
    Id: 34,
    name: "Nidoking",
    type: "Poison/Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png",
    tag: "034",
    bgColor: "purple",
  },
  {
    Id: 35,
    name: "Clefairy",
    type: "Fairy",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png",
    tag: "035",
    bgColor: "pink",
  },
  {
    Id: 36,
    name: "Clefable",
    type: "Fairy",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png",
    tag: "036",
    bgColor: "pink",
  },
  {
    Id: 37,
    name: "Vulpix",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png",
    tag: "037",
    bgColor: "red",
  },
  {
    Id: 38,
    name: "Ninetales",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png",
    tag: "038",
    bgColor: "red",
  },
  {
    Id: 39,
    name: "Jigglypuff",
    type: "Normal/Fairy",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png",
    tag: "039",
    bgColor: "pink",
  },
  {
    Id: 40,
    name: "Wigglytuff",
    type: "Normal/Fairy",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png",
    tag: "040",
    bgColor: "pink",
  },
  {
    Id: 41,
    name: "Zubat",
    type: "Poison/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png",
    tag: "041",
    bgColor: "purple",
  },
  {
    Id: 42,
    name: "Golbat",
    type: "Poison/Flying",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png",
    tag: "042",
    bgColor: "purple",
  },
  {
    Id: 43,
    name: "Oddish",
    type: "Grass/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png",
    tag: "043",
    bgColor: "green",
  },
  {
    Id: 44,
    name: "Gloom",
    type: "Grass/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png",
    tag: "044",
    bgColor: "green",
  },
  {
    Id: 45,
    name: "Vileplume",
    type: "Grass/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png",
    tag: "045",
    bgColor: "green",
  },
  {
    Id: 46,
    name: "Paras",
    type: "Bug/Grass",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png",
    tag: "046",
    bgColor: "darkgreen",
  },
  {
    Id: 47,
    name: "Parasect",
    type: "Bug/Grass",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png",
    tag: "047",
    bgColor: "darkgreen",
  },
  {
    Id: 48,
    name: "Venonat",
    type: "Bug/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png",
    tag: "048",
    bgColor: "purple",
  },
  {
    Id: 49,
    name: "Venomoth",
    type: "Bug/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png",
    tag: "049",
    bgColor: "purple",
  },
  {
    Id: 50,
    name: "Diglett",
    type: "Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png",
    tag: "050",
    bgColor: "brown",
  },
  {
    Id: 51,
    name: "Dugtrio",
    type: "Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png",
    tag: "051",
    bgColor: "brown",
  },
  {
    Id: 52,
    name: "Meowth",
    type: "Normal",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
    tag: "052",
    bgColor: "gray",
  },
  {
    Id: 53,
    name: "Persian",
    type: "Normal",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png",
    tag: "053",
    bgColor: "gray",
  },
  {
    Id: 54,
    name: "Psyduck",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png",
    tag: "054",
    bgColor: "blue",
  },
  {
    Id: 55,
    name: "Golduck",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png",
    tag: "055",
    bgColor: "blue",
  },
  {
    Id: 56,
    name: "Mankey",
    type: "Fighting",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png",
    tag: "056",
    bgColor: "brown",
  },
  {
    Id: 57,
    name: "Primeape",
    type: "Fighting",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png",
    tag: "057",
    bgColor: "brown",
  },
  {
    Id: 58,
    name: "Growlithe",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png",
    tag: "058",
    bgColor: "red",
  },
  {
    Id: 59,
    name: "Arcanine",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png",
    tag: "059",
    bgColor: "red",
  },
  {
    Id: 60,
    name: "Poliwag",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png",
    tag: "060",
    bgColor: "blue",
  },
  {
    Id: 61,
    name: "Poliwhirl",
    type: "Water",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png",
    tag: "061",
    bgColor: "blue",
  },
  {
    Id: 62,
    name: "Poliwrath",
    type: "Water/Fighting",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png",
    tag: "062",
    bgColor: "blue",
  },
  {
    Id: 63,
    name: "Abra",
    type: "Psychic",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png",
    tag: "063",
    bgColor: "purple",
  },
  {
    Id: 64,
    name: "Kadabra",
    type: "Psychic",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png",
    tag: "064",
    bgColor: "purple",
  },
  {
    Id: 65,
    name: "Alakazam",
    type: "Psychic",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
    tag: "065",
    bgColor: "purple",
  },
  {
    Id: 66,
    name: "Machop",
    type: "Fighting",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png",
    tag: "066",
    bgColor: "brown",
  },
  {
    Id: 67,
    name: "Machoke",
    type: "Fighting",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png",
    tag: "067",
    bgColor: "brown",
  },
  {
    Id: 68,
    name: "Machamp",
    type: "Fighting",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png",
    tag: "068",
    bgColor: "brown",
  },
  {
    Id: 69,
    name: "Bellsprout",
    type: "Grass/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png",
    tag: "069",
    bgColor: "green",
  },
  {
    Id: 70,
    name: "Weepinbell",
    type: "Grass/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png",
    tag: "070",
    bgColor: "green",
  },
  {
    Id: 71,
    name: "Victreebel",
    type: "Grass/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png",
    tag: "071",
    bgColor: "green",
  },
  {
    Id: 72,
    name: "Tentacool",
    type: "Water/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png",
    tag: "072",
    bgColor: "blue",
  },
  {
    Id: 73,
    name: "Tentacruel",
    type: "Water/Poison",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png",
    tag: "073",
    bgColor: "blue",
  },
  {
    Id: 74,
    name: "Geodude",
    type: "Rock/Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png",
    tag: "074",
    bgColor: "brown",
  },
  {
    Id: 75,
    name: "Graveler",
    type: "Rock/Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png",
    tag: "075",
    bgColor: "brown",
  },
  {
    Id: 76,
    name: "Golem",
    type: "Rock/Ground",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png",
    tag: "076",
    bgColor: "brown",
  },
  {
    Id: 77,
    name: "Ponyta",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png",
    tag: "077",
    bgColor: "red",
  },
  {
    Id: 78,
    name: "Rapidash",
    type: "Fire",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png",
    tag: "078",
    bgColor: "red",
  },
  {
    Id: 79,
    name: "Slowpoke",
    type: "Water/Psychic",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png",
    tag: "079",
    bgColor: "pink",
  },
  {
    Id: 80,
    name: "Slowbro",
    type: "Water/Psychic",
    img: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png",
    tag: "080",
    bgColor: "pink",
  },
];
